---
- name: Install Docker from official Docker repository
  hosts: all
  become: true
  roles:
    - install_docker

  tasks:
    - name: Install UFW
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: true

- name: Run mariadb docker containers
  hosts: dbservers
  become: true
  roles:
    - mariadb_docker

  tasks:
    - name: Allow port 3306
      community.general.ufw:
        rule: allow
        port: "3306"
        proto: tcp
    - name: Allow port 22
      community.general.ufw:
        rule: allow
        port: "22"
        proto: tcp
    - name: Ensure UFW is enabled
      community.general.ufw:
        state: enabled

- name: Run phpmyadmin docker containers
  hosts: managementservers
  become: true
  roles:
    - phpmyadmin_docker

  tasks:
    - name: Allow port 80
      community.general.ufw:
        rule: allow
        port: "80"
        proto: tcp
    - name: Allow port 22
      community.general.ufw:
        rule: allow
        port: "22"
        proto: tcp
    - name: Ensure UFW is enabled
      community.general.ufw:
        state: enabled

- name: Run web-app docker containers
  hosts: webservers
  become: true
  roles:
    - web_docker

  tasks:
    - name: Allow port 80
      community.general.ufw:
        rule: allow
        port: "80"
        proto: tcp
    - name: Allow port 22
      community.general.ufw:
        rule: allow
        port: "22"
        proto: tcp
    - name: Ensure UFW is enabled
      community.general.ufw:
        state: enabled
